### ISSUE TITLE
crash when rendering vgui scoreboard 

### ISSUE THREAD

**Issue by mittorn** [SDLash3D/xash3d#37]
When trying to show vgui scoreboard in few first seconds of client run (or under console animation), it crashes.
```
#0  FontCache::AllocatePageForChar (this=this@entry=0xf7784600 <g_FontCache>, 
    charWide=charWide@entry=141908808, charTall=charTall@entry=1431655765, 
    pageIndex=@0xffffc7b8: 0, drawX=@0xffffc7bc: 157750536, 
    drawY=@0xffffc7c0: -134306051, twide=@0xffffc7c4: -172564480, 
    ttall=@0xffffc7c8: -1) at client/vgui/vgui_font.cpp:127
        page = @0x0: <error reading variable>
        nPageType = -1
        nNextX = 0
        bNeedsNewPage = true
        page = @0x0: <error reading variable>
#1  0xf5b26cad in FontCache::GetTextureForChar (this=0xf7784600 <g_FontCache>, 
    font=0x9671078, ch=117 'u', textureID=0xffffc848, texCoords=0xffffc84c)
    at client/vgui/vgui_font.cpp:76
        a = -189897080
        drawX = 157750536
        twide = -172564480
        nByteCount = <optimized out>
        b = 141908808
        fontWide = 141908808
---Type <return> to continue, or q <return> to quit--- 
        cacheHandle = <optimized out>
        fontTall = 1431655765
        c = -173898600
        drawY = -134306051
        rgba = <optimized out>
#2  0xf5b25cb2 in CEngineSurface::drawPrintText (this=0x8a63a50, 
    text=0xffffc8dc "u", textLen=1) at client/vgui/vgui_surf.cpp:198
        texCoords = 0xf778464c <FontCache::GetTextureForChar(vgui::Font*, char, int*, float**)::cacheitem+8>
        lr = {point = {3.60133705e-43, 4.44860511e-34}, coord = {
            4.70204536e-34, 4.4466637e-34}}
        clippedRect = {{point = {0, 0}, coord = {0, 1}}, {point = {0, 
              -8.90794975e+33}, coord = {-1.31875277e+32, -1.31875277e+32}}}
        iTexId = 0
        ul = {point = {4.44860511e-34, -nan(0x7fc880)}, coord = {
            2.24207754e-44, 4.70488124e-34}}
        abcB = 135513096
        ch = 117 'u'
        abcA = -191664844
        abcC = 136070212
        iWide = 135513096
        i = 0
        y = -715827775
```

**Comment by mittorn** [comment]
Seems to be solved
