### ISSUE TITLE
Crash on dlclose in vgui

### ISSUE THREAD

**Issue by mittorn** [SDLash3D/xash3d#38]
```
Program received signal SIGSEGV, Segmentation fault.
0xf7e2e6b0 in main_arena () from /lib32/libc.so.6
(gdb) bt full
#0  0xf7e2e6b0 in main_arena () from /lib32/libc.so.6
No symbol table info available.
#1  0xf59fb1f5 in getFont (this=0x9939038)
    at ../utils/vgui/lib-src/vgui/TextImage.cpp:87
No locals.
#2  vgui::TextImage::getFont (this=0x9939038)
    at ../utils/vgui/lib-src/vgui/TextImage.cpp:83
No locals.
#3  0xf59fad26 in vgui::TextImage::getTextSize (this=0x9939038, 
    wide=@0xffffc134: 0, tall=@0xffffc13c: 0)
    at ../utils/vgui/lib-src/vgui/TextImage.cpp:324
        font = <optimized out>
#4  0xf186c843 in CTextImage2::getSize (this=0x9938fa8, wide=@0xffffc1a0: 16, 
    tall=@0xffffc1a4: -1) at ../cl_dll/vgui_ScorePanel.h:56
        w1 = 0
        w2 = 0
        t1 = -2139454594
        t2 = 0
#5  0xf59ec548 in vgui::Label::computeAlignment (this=0x98fc570, 
    tx0=@0xffffc210: 0, ty0=@0xffffc214: 56, tx1=@0xffffc218: 0, 
    ty1=@0xffffc21c: 0, ix0=@0xffffc220: 0, iy0=@0xffffc224: -136555060, 
    ix1=@0xffffc228: -185581568, iy1=@0xffffc22c: -185675381, 
    minX=@0xffffc230: 4104, minY=@0xffffc234: 134569544, 
---Type <return> to continue, or q <return> to quit---
    maxX=@0xffffc238: -15380, maxY=@0xffffc23c: -136125376)
    at ../utils/vgui/lib-src/vgui/Label.cpp:156
        tWide = <optimized out>
        tTall = <optimized out>
        offX = <optimized out>
        offY = <optimized out>
        pad = <optimized out>
        wide = <optimized out>
        tall = <optimized out>
        iWide = 0
        iTall = 139994640
#6  0xf59ec3e5 in vgui::Label::getContentSize (this=0x98fc570, 
    wide=@0xffffc268: 1, tall=@0xffffc26c: -134721536)
    at ../utils/vgui/lib-src/vgui/Label.cpp:104
        ty0 = 56
        tx1 = 0
        iy1 = -185675381
        minY = 134569544
        maxX = -15380
        ty1 = 0
        ix0 = 0
        minX = 4104
        tx0 = 0
---Type <return> to continue, or q <return> to quit---
        iy0 = -136555060
        ix1 = -185581568
        maxY = -136125376
#7  0xf59ecbe3 in vgui::Label::recomputeMinimumSize (this=0x98fc570)
    at ../utils/vgui/lib-src/vgui/Label.cpp:419
        wide = 1
        tall = -134721536
#8  0xf59ec474 in vgui::Label::setImage (this=0x98fc570, image=0x0)
    at ../utils/vgui/lib-src/vgui/Label.cpp:120
No locals.
#9  0xf187e2ec in CVoiceStatus::FreeBitmaps (this=0xf18e3ea0 <g_VoiceStatus>)
    at ../cl_dll/voice_status.cpp:822
        i = <optimized out>
#10 0xf187e950 in CVoiceStatus::~CVoiceStatus (
    this=0xf18e3ea0 <g_VoiceStatus>, __in_chrg=<optimized out>)
    at ../cl_dll/voice_status.cpp:170
No locals.
#11 0xf7cb918b in __cxa_finalize (d=0xf18be300) at cxa_finalize.c:55
        cxafn = <optimized out>
        cxaarg = <optimized out>
        f = 0xf7e2f2a8 <initial+200>
        funcs = 0xf7e2f1e0 <initial>
#12 0xf182b134 in __do_global_dtors_aux () from valve/cl_dlls/client.so
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#13 0xf18999d1 in _fini () from valve/cl_dlls/client.so
No symbol table info available.
#14 0x0804bc38 in ?? ()
No symbol table info available.
#15 0xf7ff0c58 in _dl_close (_map=0x8b24a98) at dl-close.c:775
        map = 0x8b24a98
        __PRETTY_FUNCTION__ = "_dl_close"
#16 0xf7f8df92 in dlclose_doit (handle=handle@entry=0x8b24a98) at dlclose.c:36
No locals.
#17 0xf7feb27e in _dl_catch_error (objname=0xf7f9106c <last_result+12>, 
    errstring=0xf7f91070 <last_result+16>, 
    mallocedp=0xf7f91068 <last_result+8>, operate=0xf7f8df70 <dlclose_doit>, 
    args=0x8b24a98) at dl-error.c:177
        errcode = 0
        old = 0xffffc998
        c = {objname = 0xf7decffb "corrupted double-linked list", 
          errstring = 0x0, malloced = 6, env = {{__jmpbuf = {-134230080, 
                -134672288, -134230912, 145902232, -15008, -134303141}, 
              __mask_was_saved = 0, __saved_mask = {__val = {4160641056, 
                  4160737216, 134524960, 5, 4122403812, 4160661436, 134525400, 
                  0, 4160641056, 4160737216, 134524960, 5, 4122404356, 
                  4158376213, 4122402816, 4122018218, 136594392, 0, 2, 6, 
---Type <return> to continue, or q <return> to quit---
                  4160641056, 4122402816, 136594392, 4121903919, 136594392, 0, 
                  2, 4122199858, 594, 4120644344, 145111660, 7995}}}}}
        catchp = 0xf7c836ec
#18 0xf7f8e5e2 in _dlerror_run (operate=<optimized out>, args=0x8b24a98)
    at dlerror.c:163
        result = 0xf7f91060 <last_result>
```

**Comment by mittorn** [comment]
Fixed
